### ISSUE TITLE
combine map with list view a-z and Category type select

### ISSUE THREAD

**Issue by morange** [SicorDev/sic_address#48]
Hello,

i would like to combine the map view (more then one location) with the option to select the entries by categories and with the selection about a-z. And i would like to use the map on the single page for the location.

Many things, is it possibile and how? It would be great if you can give some hints.

I use TYPO3 v10.4, tt_address v5.1.2 and sic_address v3.1.2

Beste greetings and many thanks
m.orange

**Comment by SicorDev** [comment]
Hello, I don't know why, but back then did my workmate create a separate new map action instead of just enhancing list view.
I have a pretty cool variant going Live soon, but unfortunately it still doesn't incorporate a-z filters.

WIP: https://neu.massivholzmauer.de/de/kontakt/hersteller-/-partner-finden

**Comment by morange** [comment]
Hello SicorDev, many thanks for your response. It's not too bad at the moment.

**Comment by SicorDev** [comment]
History in the making, but I just released Version 4.0.0 of the extension for TYPO3 11. It finally has the map fully integrated into the list action, so You can combine all elements as you please.

Not sure about integrating the map into "Show" - should be just a matter of creating a fitting template. You probably already have one?
