### ISSUE TITLE
Error: The action "search" is not allowed by this plugin

### ISSUE THREAD

**Issue by Hobokens** [SicorDev/sic_address#50]
Hi,
after updating sic_address I get the following error:
`Core: Exception handler (WEB): Uncaught TYPO3 Exception: #1313855175: The action "search" (controller "SICOR\SicAddress\Controller\AddressController") is not allowed by this plugin / module. Please check TYPO3\CMS\Extbase\Utility\ExtensionUtility::configurePlugin() in your ext_localconf.php / TYPO3\CMS\Extbase\Utility\ExtensionUtility::configureModule() in your ext_tables.php. | TYPO3\CMS\Extbase\Mvc\Exception\InvalidActionNameException thrown in file /var/www/vhosts/xxxx.aaa-bbb.de/httpdocs/typo3cms/typo3_src-10.4.24/typo3/sysext/extbase/Classes/Mvc/Web/RequestBuilder.php in line 308. Requested URL: https://www.my-domain.de/lehre/N `

There is no problem to use the search with a-z-view. (sicorlist).

TYPO3 10.4.24
sic_address 3.2.
tt_address 5.3.

**Comment by SicorDev** [comment]
Hm... weird... That error should come only when updating to TYPO3 11, not when updating sic_address...

Maybe it's because of the routing? 1: Did you try disabling that? I just updated the sicorlist template to use the A-Z Partial. I think that's required for the routing to work. 2: Can you try SicorList.HTML from my last commit?

That's all I can think of right now.

**Comment by SicorDev** [comment]
#3: Is it only an error in debug mode and worksLive, can you try that?

**Comment by Hobokens** [comment]
Thanks for checking this out. I will first disable the debug mode and report the result after a few days.

**Comment by Hobokens** [comment]
Disabling the debug mode didn't solve the issue, but switching to the A-Z Partial did it.
Thanks for your help!

**Comment by Hobokens** [comment]
I'm sorry, I just got the error message error again :-(

**Comment by Hobokens** [comment]
Removing the routing enhancer doesn't solve the problem. I still get an error message:

`Core: Exception handler (WEB): Uncaught TYPO3 Exception: #1313855175: The action "search" (controller "SICOR\SicAddress\Controller\AddressController") is not allowed by this plugin / module. Please check TYPO3\CMS\Extbase\Utility\ExtensionUtility::configurePlugin() in your ext_localconf.php / TYPO3\CMS\Extbase\Utility\ExtensionUtility::configureModule() in your ext_tables.php. | TYPO3\CMS\Extbase\Mvc\Exception\InvalidActionNameException thrown in file /var/www/vhosts/xxxxxxx.my-hosting.de/httpdocs/typo3cms/typo3_src-10.4.26/typo3/sysext/extbase/Classes/Mvc/Web/RequestBuilder.php in line 308. Requested URL: https://www.my-domain.de/lehre?tx_sicaddress_sicaddress%%5Baction%%5D=search&tx_sicaddress_sicaddress%%5Batoz%%5D=N&tx_sicaddress_sicaddress%%5Bcontroller%%5D=Address `

**Comment by SicorDev** [comment]
Since the classloading has changed some since we wrote this extension, we now went ahead porting it to TYPO3 11. I don't think we did anything breaking for TYPO3 10, so could you possibyl give it a try and see if your problem is gone with it too? 
Please have it from the master here, it's too fresh for a TER release.

**Comment by SicorDev** [comment]
I see you switched to 11, so I'm closing this issue.
