### ISSUE TITLE
No output in Frontend

### ISSUE THREAD

**Issue by jumping-blueberry** [SicorDev/sic_address#7]
Dear developers,

I hope you can help me with my issue.

I had an old tt_address (we were working with Typo3 4.5 before) and added sic_address.
We are now on Typo3 8.7.10

tt_address 3.2.2
sic_address 1.1.2

I imported the tt_address field definition and added new fields.
In the process of understanding the module, I pressed the "Generate Model..." - Button but also the "Clear Field Definition"-Button a few times.
The tt_address-fields do not show up in the backend-module. I'm not sure if this is supposed to be this way.

The special fields are recognized in a new tab when entering a new address.

I set custom templates and they are used. 
The records (Datensätze) are found but everything like {address.name} is not displayed.

Could it be an issue with messed up database-tables?
How could I reset this (un-installing the extensions doesn't change the database)

Thanks in advance
jumping-blueberry

P.S. Antwort auf Deutsch ist in Ordnung. Wenn ich Screenshots o.ä. schicken soll, einfach Bescheid sagen ;-)

**Comment by SicorDev** [comment]
Hallo, spannendes Problem, auf das ich auch keine sofort Antwort habe...

Nimmst das List Plugin? Versuche doch da mal ein
<f:debug>{addresses}</f:debug>

**Comment by jumping-blueberry** [comment]
Ja, ich habe die Listen-Ansicht gewählt
<f:debug>{addresses}</f:debug>gibt gar nichts aus.

Wenn ich allerdings <f:debug>{address}</f:debug> in die Schleife schreibe, sieht man, nur die Felder, die ich angelegt habe.
Auch hatte ich Feldnamen mit Unterstrich (z.B. sorter_seite) welche in Camel-Case umbenannt wurden (sorterSeite)

Das Plugin soll auf der Seite mehrfach eingebunden werden (verschiedene Kategorien)

Ich hänge mal einen Screenshot der Ausgabe von 2 Datensätzen an. 

Ich hoffe, Ihr könnt mir helfen... ich schlage mich schon seit 2 Tagen damit rum und komme nicht weiter.

LG
jumping-blueberry 

![bildschirmfoto 2018-06-14 um 18 38 03](https://user-images.githubusercontent.com/40266835/41425820-1fcd467a-7002-11e8-9195-29ec2dfbca90.png)

**Comment by SicorDev** [comment]
Okay... nach nochmaligem Lesen der Beschreibung wird es mir klar: "Clear Field Definition" hat auch die zuvor importierten tt_address Feld-Mappings wieder gelöscht - es löscht wirklich *alle* Felddefinitionen.

Ich würde folgendes Vorgehen vorschlagen:

#1: Den tt_address import Button nochmal drücken. Damit verschwinden die neu angelegten Felder wieder, ist aber der einzige Weg, die tt_address Felder erneut zu mappen.
#2: Jetzt die 6 Felder eins nach dem anderen wieder anlegen, jedesmal in der Zeile Save klicken.
#3: Zuletzt den "Generate Model..." Button drücken.

Ich denke ich werde mit einem Update mal den "Clear Field Definition" Button umstellen, so dass da keine tt_address Mappings mehr gelöscht werden. Und einen zweiten Button hinzufügen, falls man tatsächlich die tt_address Mappings löschen möchte...

Um noch die Frage eingangs zu beantworten: Daß man die tt_address Felder nicht sieht, ist by Design. Wir möchten diese bewusst nicht anfassen und die Verantwortung hier beim Entwickler von tt_address belassen. Falls tt_address mal eingestellt wird, können wir ja einen komplett Import nachrüsten oder so, aber im Moment setzen wir auf friedliche Koexistenz.

**Comment by SicorDev** [comment]
Hm... ganz so einfach ist es nicht, sehe ich gerade. Ich ergänze mal:

#1: Clear Field Definition klicken.
#2: "Generate Model..." Button drücken.
#3: Mit dem Database Analyzer im Install Tool die neuen Felder aus tt_address erstmal wieder entfernen
#4: Den tt_address import Button drücken. 
#5: Jetzt die 6 Felder eins nach dem anderen wieder anlegen, jedesmal in der Zeile Save klicken.
#6: Zuletzt den "Generate Model..." Button drücken.

Am besten niemals wieder den Clear Button verwenden... Besser ich entferne den ganz.

**Comment by SicorDev** [comment]
A week without feedback, so we're closing this. We uploaded a version 1.1.3, which has two separate "clear fields" buttons to minimize future risk of this happening again.
